[book]
authors = ["abeRodz"]
language = "en"
multilingual = false
src = "src"
title = "STM32 MS5611 LCD"

[output.html]
default-theme = "dark"
preferred-dark-theme = "ayu"
site-url = "/"
cname = ""

[output.html.print]
enable = false

[output.html.fold]
enable = true
level = 0